var FPS_TIME = 1000/24;
var BONUS_TIME = 12000;
var HINT_PENALTY = 10;

//ENGLISH
var LANGUAGE = "en_UK";
//GERMAN
//var LANGUAGE = "de_DE";
//SPANISH
//var LANGUAGE = "es_ES";
//FRENCH
//var LANGUAGE = "fr_FR";
//ITALIAN
//var LANGUAGE = "it_IT";
//DUTCH
//var LANGUAGE = "nl_NL";
//PORTUGUESE
//var LANGUAGE = "pt_PT";

var SCORE_BONUS_LAYOUT_EASY   = 1;
var SCORE_BONUS_LAYOUT_MEDIUM = 2;
var SCORE_BONUS_LAYOUT_HARD   = 3;

var MSG_BOX_MODE_OK     = 1;
var MSG_BOX_MODE_YES_NO = 2;

var ON_MSGBOX_EXIT_FROM_GAME = "ON_MSGBOX_EXIT_FROM_GAME";
var ON_MSGBOX_NOT_EXIT_FROM_GAME = "ON_MSGBOX_NOT_EXIT_FROM_GAME";